### ISSUE TITLE
Rounding of numeric display not consistent between Mobile app (Apple) and Web

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#11]
Rounding of numeric display not consistent between Mobile app (Apple) and Web. 

On Mobile App(Apple) shows a value for my SOL balance:

![image](https://github.com/Power-Trade/api-docs/assets/5905130/55a991a2-2b46-47fc-a104-d3e9b967690a)

On Web UI shows as 

![image](https://github.com/Power-Trade/api-docs/assets/5905130/b5b1cd1e-ac18-4197-b832-560131cce197)

Minor issue, some consistency would be better across the UIs

**Comment by trungpwt** [comment]
@laisee, could you please share screenshots full-screen displaying this price in the iOS app?

**Comment by laisee** [comment]
Sure, will add full size screenshots from IOS App

**Comment by laisee** [comment]
![power-trade-IOS-02](https://github.com/Power-Trade/api-docs/assets/5905130/71fd293f-4b14-44fb-940a-03b85ecd1c83)
![power-trade-IOS-01](https://github.com/Power-Trade/api-docs/assets/5905130/d204205f-2975-4315-bf4b-a649ee7cf2aa)

**Comment by klugjo** [comment]
@trungpwt this is a web issue.

Sizes in the positions table are always rounded down. Fixing now

**Comment by klugjo** [comment]
@laisee this is now fixed. Can you confirm ? Thanks

**Comment by laisee** [comment]
Web and App (IOS) displays now consistent for rounded values ("21.07" on both web && app)

**Comment by laisee** [comment]
Web and App (IOS) displays now consistent for rounded values ("21.07" on both web && app)
