### ISSUE TITLE
Test app doesn't load Portfolio UI (Version 3.0.9, Testflight)

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#22]
Test app doesn't load Portfolio UI (Version 3.0.9)

Using testflight to load app version 3.0.9. Loading display shows but Portfolio is never displayed.

'Markets' loads ok
'My funds; also fails to loads
User settings loads ok

![v3 0 9-2](https://github.com/Power-Trade/api-docs/assets/5905130/fe64f97e-f67e-442e-ba19-0c80d4e45a58)

![v3 0 9-1](https://github.com/Power-Trade/api-docs/assets/5905130/f83e5246-77b8-4f95-ace2-d42f2fa33758)

**Comment by trungpwt** [comment]
@laisee  Does this happen all the time or just once? I'm guessing this can occur when you try to use the app while our system is upgrading because it's the TEST environment. How is it now?

**Comment by laisee** [comment]
I checked again, the "portfolio" UI doesn't finish loading. 'Markets' loads in about 5 seconds. 'My Funds' also fails to complete loading.

**Comment by laisee** [comment]
working now.
