### ISSUE TITLE
Selling SOL coin to myself in SPOT market generates 2 BUY trade records

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#24]
Selling SOL to myself generates 2 trade records but both are displayed as BUY trades

See below, 2 trade records for 23/2/2024 and 2 for 20/2/2024.  I made two trades selling 1 X SOL to myself at prices  188, 198 on 20/2 and 23/2.

I would expect this kind of trade to generate 1 X BUY and 1 X SELL record but instead the Web UI  (below) and IOS app show all trades were BUY. 

<img width="1166" alt="Screenshot 2024-02-23 at 3 23 05 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/5d42b809-1cd1-44c9-9d54-2f7ddfa8f623">

Side 1 (from IOS v3.0.8)

![image](https://github.com/Power-Trade/api-docs/assets/5905130/a31a2682-8ee8-4c64-a627-2070efcc3705)

Side 2(from IOS v3.0.8)

![image](https://github.com/Power-Trade/api-docs/assets/5905130/a085d00e-e8fb-4135-bcb5-c7c7e289b57f)

**Comment by klugjo** [comment]
This is fixed on web where it shows `Self` and only one entry.

Looks like it still needs work on mobile:

![image](https://github.com/Power-Trade/api-docs/assets/2960040/57926ff2-58c7-4f81-a282-e9efebdb60e7)

**Comment by klugjo** [comment]
@trungpwt

**Comment by laisee** [comment]
Tested on PROD Web app for AVX coin in SPOT market

Single trade record created now with correct price/volume/fee and side shows as 'self'

![image](https://github.com/Power-Trade/api-docs/assets/5905130/27a336b5-1258-42f1-9237-4a86b3427558)

Tested oN IOS app also and same record appears in Trade History (Web) which is correct. But trade history on IOS app shows 4 records for buy/sell @ quantity = 0.1 and 1.0

<img width="1164" alt="Screenshot 2024-04-25 at 14 52 31" src="https://github.com/Power-Trade/api-docs/assets/5905130/602a4419-cea6-49d8-849a-c00026e64c4c">

**Comment by laisee** [comment]
Tested again using Web UI and IOS mobile app. 

Web shows single trade with correct values for side, commission, quantity etc

IOS App shows two trades, one with valid commission amount and one with commission = "FREE". 

**Trade on Web UI showing one trade and correct commission amount**

<img width="1068" alt="Screenshot 2024-07-22 at 16 30 35" src="https://github.com/user-attachments/assets/738442c1-867d-4d2a-83d5-54d977b446de">


**Trade on IOS App showing FREE commission**

![image](https://github.com/user-attachments/assets/c5f54abb-9819-4f90-8220-5fb57835d006)
 

**Two trades on IOS App**

![image](https://github.com/user-attachments/assets/bd38b9a4-b120-4d69-b975-dc3050215000)

**Comment by laisee** [comment]
Resolved
