### ISSUE TITLE
Information sent between cycle_starting/started and cycle_ending/ended

### ISSUE THREAD

**Issue by chriskohlhoff** [Power-Trade/api-docs#3]
Was just looking at that market data sequence diagram, but this may apply to the other protocols as well. It may be worth listing the kinds of messages you can receive between the `cycle_starting`/`started` and `cycle_ending`/`ended` pairs. For example, here:

https://github.com/Power-Trade/api-docs/blob/d286369422c5794fb2ac87fe796c66bf01852736/protocols/puml/market_data_protocol.puml#L38-L39

In general the following between `cycle_starting` and `cycle_started` you will receive information that "carries over" from before the cycle started. For market data this means:

* Reference data for existing deliverables and and tradeable entities (e.g. `deliverable`, `tradeable_entity`).
* The state of the tradeable entities as the beginning of the cycle (`trading_state`).
* Restatement of display orders that were already open before the cycle started (`display_order_added`).
* Top of book information if there are open orders (`top_of_book`).

After `cycle_started`, we're now in the real-time market data phase, which can include new reference data (e.g. for newly added options), as well as any of the other messages.

Between `cycle_ending` and `cycle_ended` you may receive deletions for orders that are expiring (`display_order_deleted` for orders who have reached the end of their `good_for_cycles`).

**Comment by kernelbee** [comment]
@chriskohlhoff : thank you very much again; the mentioned suggestion is implemented and can be reviewed in: https://github.com/Power-Trade/api-docs/commit/5716d0054764b6c619c42e04b6bab4aa0df9d923

**Comment by kernelbee** [comment]
+ https://github.com/Power-Trade/api-docs/commit/03771e95d4e7295f24f70b16f9e9896943593681

**Comment by kernelbee** [comment]
Was addressed, so closing as done
