### ISSUE TITLE
Clicking on one row of History page data causes more than one row to be expanded (minor issue)

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#30]
As per the Title.

See example below for expanded rows 

<img width="1145" alt="Screenshot 2024-03-14 at 11 15 09 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/c5e65aa9-8820-4ee7-9722-4493c7897826">

**Comment by laisee** [comment]
Also saw multiple rows expanded when clicking on one row

<img width="1145" alt="Screenshot 2024-03-14 at 11 15 09 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/e8dba9d0-7e9b-4fb9-bde6-577a0a5aedaa">

**Comment by laisee** [comment]
Testing this issue again. Can be seen on PT site but not at  Bitmex/PT UI.

**Comment by klugjo** [comment]
I did improve this. it can't be fixed 100% due to the use of composite ids instead of unique ids for each row.

Considering this minor enough to close and ignore. Thanks for reporting as always 💯
