### ISSUE TITLE
Inconsistent decimal display setting between 'Portfolio' and 'Funds' pages

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#33]
Funds page allows up to 10 decimal places for wallet balances, while Portfolio page has a setting of 4 decimal places. 

Also, the same page will show 2 decimal places for some coins and 

 - understand this may be a deliberate choice but a) is it really useful for users? b) full value could be displayed using mouse over
 - another option might be to allow users to set the display by choosing how many decimal places they want to view

<img width="354" alt="Screenshot 2024-03-20 at 2 28 17 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/e55ca88c-c386-457d-8ad9-be86dd82c27b">

Portfolio display 

<img width="460" alt="Screenshot 2024-03-20 at 2 26 31 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/41fe742c-ea03-4462-9700-c8ba493a5e7d">

Funds display

<img width="899" alt="Screenshot 2024-03-20 at 2 26 52 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/929b91a0-0aa3-4481-bf6b-ad9324a1c938">

A good, simple guide for UX of numbers in tables

https://medium.com/@hagan.rivers/6-ways-to-improve-usability-of-numbers-in-tables-9688aaca6866

**Comment by klugjo** [comment]
Cleaned up the funds page with proper decimal places and hover on values to see/copy all decimals (same as trading screens header)


![image](https://github.com/Power-Trade/api-docs/assets/2960040/c7cca431-12fc-406d-a2d1-597f3804290d)

**Comment by laisee** [comment]
Closing as fixed in PROD (web)
