### ISSUE TITLE
Positions display is confusing due to range of colors and symbols used

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#34]
Positions display is confusing due to range of colors and symbols used

- First record shows a short call option trade. Confusing because it seems to be a loss but arrow head to the right is green

![image](https://github.com/Power-Trade/api-docs/assets/5905130/8c3d8245-7caf-48ab-af3f-907a7e695b62)

- Second record shows a long put options trade with profit. Confusing because the arrow head to the right is red

![image](https://github.com/Power-Trade/api-docs/assets/5905130/1f1411a5-79ea-4cd9-ae12-039b3d9c55c7)

- Third record shows a SOL Perpetual trade with $95 loss. Confusing because it shows a green arrow to the right and upward arrow next next to the trade title ("SOL Perps").

- Fourth record has same issues as first one i.e. loss on Options trade has green arrow head on right side

**Full screen shot of the Positions tab**

![power-trade-positions-confused](https://github.com/Power-Trade/api-docs/assets/5905130/3d8f5066-8f48-4839-b35f-df07f8984d3b)

**Comment by trungpwt** [comment]
This has been fixed and is ready for testing in the TEST versions. Could you please use the version that is ready to download from TestFlight? Unable to publish a new version on Appstore due to some reasons now.

**Comment by laisee** [comment]
Sure, will download and test today. Assuming version 3.1.0 (3046) is the latest?
