### ISSUE TITLE
Error when generating deposit address on Bitmex/PT Options UI

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#36]
Error when generating deposit address on Bitmex/PT Options UI. Clicked from warning message about account being at risk of liquidation.

**1.  Removed 100 USDT from Options account, which caused account health to go down to 10% and show this messages**

 

<img width="675" alt="Screenshot 2024-04-01 at 11 07 58 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/61abc9be-3344-42ed-81d8-d5bb1f77fb85">

**2. Clicked on "Deposit Now" which showed UI for depositing USDT/USDC/BTC [tried all 3 coins, all showed error]**

<img width="673" alt="Screenshot 2024-04-01 at 11 07 29 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/056f8b80-b240-4d40-b5bb-d651d6a2353d">

**3.  UI also showing an error message for generating deposit address. See image above**

Error may stop people making deposits to rescue their Options account. Also there is no link to the same "Fund Options" UI.

**Comment by trungpwt** [comment]
I received 2 issues that forwarded to me but seems this report is for web @klugjo

**Comment by klugjo** [comment]
Thanks will fix

**Comment by klugjo** [comment]
This is fixed

**Comment by laisee** [comment]
confirmed as fixed, now "Deposit" button is disabled.

<img width="504" alt="Screenshot 2024-04-26 at 16 04 18" src="https://github.com/Power-Trade/api-docs/assets/5905130/a67e1259-d76b-4173-ab0e-bc133787d1ec">
