### ISSUE TITLE
Market data not displayed in "New Listings" & "Markets" sections on Portfolio page (Web)

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#39]
![image](https://github.com/Power-Trade/api-docs/assets/5905130/5993c434-ef20-4e77-a8f2-ba072116bacc)

My 2 cents of advice would be to remove or re-design these sections under Portfolio details as users probably won't be looking here for new listings info (should be a new items or "recent product news" links on top of home page. 

See below, there is possibly free space at top right side of web page for news/events/listing/product updates - as is done by binance/bybit/others

<img width="1084" alt="Screenshot 2024-04-23 at 14 21 16" src="https://github.com/Power-Trade/api-docs/assets/5905130/a19e8af8-4961-44ba-b166-bb8476bd4525">

**Comment by klugjo** [comment]
I just removed that page as it didnt deliver on its promises

**Comment by laisee** [comment]
"Portfolio" removed from links at top of web page. Page can still be accessed by using the old link address i.e. https://app.power.trade/portfolio. Closing ticket on assumption page will be removed at server-side also.

**Comment by klugjo** [comment]
yes page is still accessible, Mario is having a think on how to improve/revamp it and we will reintroduce it again.

No harm if users "in the know" access the page in the meantime since it's a mostly readonly page

Thanks @laisee

**Comment by laisee** [comment]
Sounds good. Will update comment and keep ticket closed pending future
developments from Mario
