### ISSUE TITLE
Support web page has incorrect link for testnet 

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#40]
At [support link for PT Testnet ](https://support.power.trade/trading/margin-and-liquidation/portfolio-margin#testnet) the web link for testnet is displayed as "https://powertrade-web-test.web.app" but the actual link goes to "https://support.power.trade/how-to-use-powertrade/login/common-login-issues"

**Comment by klugjo** [comment]
Thanks for reporting, this is fixed
