### ISSUE TITLE
USDT/SPOT market visible on Power Trade DEX

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#53]
USDT/SPOT market can be traded on https://dex-app.power.trade/trade/spot/USDT-USD

Should be removed or hidden, based on comments from Mario & team. 

<img width="267" alt="Screenshot 2024-07-19 at 14 55 23" src="https://github.com/user-attachments/assets/f6b8f6e5-91d4-4ca6-8ce6-1eaec5ffe1b2">

**Comment by klugjo** [comment]
done
