### ISSUE TITLE
Observations on latest Mobile App (OSX)

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#57]
**1. Total Funds(Equity) does not always load all assets and possitions**

Could be linked to this issue: https://github.com/Power-Trade/api-docs/issues/16

The UI shows full amount when fully reloaded, but initial view shows only 75% of funds available. 

![power-trade-new-app-OSX](https://github.com/user-attachments/assets/45dd752a-5ed7-4201-b598-c58949e1152c)

![power-trade-new-app-OSX-2](https://github.com/user-attachments/assets/70581070-c985-46e7-87a6-b9196ba2b753)

**2. Icons seem to flicker constrantly**

Happens on "My Funds" page for mobile app (OSX) 

**3. UI seems to be looping throiugh a refresh which can be observed**

**Comment by laisee** [comment]
**Mobile App - Icons flashing**

https://github.com/user-attachments/assets/1418106b-ae3f-4e38-bb80-5aea1e9074db

**Comment by laisee** [comment]
**Mobile App - Reloading loop**


https://github.com/user-attachments/assets/8cd32c12-2bec-4b1c-adda-d59f21ed22da

**Comment by trungpwt** [comment]
@laisee could you pls verify issues on v3.2.0 (3283)?
Thanks

**Comment by laisee** [comment]
**Updates observed**

1. Total Balance lods correctly now with full balance value:
    item 1 CLOSED 
3. Flickering icons still seen on Markets and My Funds UI pages/tabs:
    item 2 OPEN
5. Reloading loop cannot be seen now:
    item 3 CLOSED

**Comment by trungpwt** [comment]
> **Updates observed**
> 
> 1. Total Balance lods correctly now with full balance value:
>    item 1 CLOSED
> 2. Flickering icons still seen on Markets and My Funds UI pages/tabs:
>    item 2 OPEN
> 3. Reloading loop cannot be seen now:
>    item 3 CLOSED

Issue 2: @laisee Could you send me a short video of that?

**Comment by laisee** [comment]
https://github.com/user-attachments/assets/a4bdc647-f5a0-43b5-a660-b62fac942754

**Comment by trungpwt** [comment]
> latest-power-trade-app-flicering-icons.mp4

<img src="https://github.com/user-attachments/assets/76abc3fe-01c8-4364-be1f-6bf01796df2c" width="320" height="768">

@laisee could you send me the screenshot of this screen? 
Also, could you please let me know the iOS version and your iPhone model?

**Comment by laisee** [comment]
IOS version: 17.6.1
Iphone version: Iphone 13
Power.Trade app version: was 3.2.0(3283) but updated to 3.2.0(3284) today

**Comment by laisee** [comment]
![power-trade-mnobile-app-3284](https://github.com/user-attachments/assets/1f5becf3-8d37-4681-881b-c657f33a0f41)

**Comment by trungpwt** [comment]
Thanks for that, and could you please verify the remaining issues in version 3.2.0 (3288)? @laisee

**Comment by laisee** [comment]
flickering icons removed in v3.2.0 (3288). Closing this
