### ISSUE TITLE
401 error when requesting user profile from PT web site

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#9]
Taken from inspection of web page content on Brave browser, showing API calls made and their error or success
Doesn't seem to be causing ahy UI issue but added here in case its connected to other issues raised.

_```
index-69707593.js:30 
        
GET https://api.rest.prod.power.trade/v1/profile 401 (Unauthorized)
```_

Browser: [Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (arm64)](https://brave.com/latest/)
Site URL: https://app.power.trade/trade/spot/SOL-USD
Call: see details above

**Comment by klugjo** [comment]
@laisee Thanks for reporting

If this happens on page load, it means that the current authentication session has expired and needs to be refreshed.

It is expected. Please reopen this ticket if this causes unexpected behaviour.

Thanks
